name: Deploy Backend
on:
  push:
    branches: 
      - main
    path:
      - 'Backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step A: Get your code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step B: Set up pyhon 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step C: Install tools 
      - name: Install AWS CLI
        run: |
          python -m pip install --upgrade pip
          pip install boto3 pytest mock
      # Step D: RUN TESTS 
      - name: Run Tests
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: testing
          AWS_SECRET_ACCESS_KEY: testing
        run: |
          cd Backend
          python test_lambda.py
      ## Step E: Zip the code
      - name: Zip Lambda Code
        run: |
          cd Backend
          # Zip everything EXCEPT junk files and the test file itself
          zip -r lambda.zip . -x "*.pyc" -x "__pycache__" -x "test_lambda.py"
      
      # Step F: Log in to AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # We use the NAME of the secret variable, NOT the key itself
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1


      # BLOCK 3: THE DEPLOY
      - name: Update Lambda Code
        run: |
          aws lambda update-function-code --function-name update_visitor_count --zip-file fileb://Backend/lambda.zip